# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-11-16 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('paisa', models.IntegerField()),
                ('rupee', models.FloatField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'paisa',
            },
        ),
    ]
